name: task_manager
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_localized_locales: ^2.0.3
  intl: ^0.17.0
  
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.9
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  rxdart: ^0.27.3
  uuid: ^3.0.6
  dio: ^4.0.4
  connectivity_plus: ^2.2.1
  jwt_decoder: ^2.0.1
  tuple: ^2.0.0
  auto_route: ^3.2.4
  json_annotation: ^4.4.0
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0

  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8

  flutter_svg: ^1.0.3
  flutter_map: ^0.14.0
  cached_network_image: ^3.2.0
  declarative_animated_list: ^0.1.1
  percent_indicator: ^4.0.0
  expandable_page_view: ^1.0.10
  tab_indicator_styler: ^2.0.0
  fl_chart: ^0.45.0
  boxy: ^2.0.5
  custom_timer: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  auto_route_generator: ^3.2.3
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  color: "#1E1F25"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
  
  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300